ruby isanagram.rb anagram_1.txt spsidebyside1.txt
ruby isanagram.rb anagram_2.txt spsidebyside2.txt
ruby isanagram.rb anagram_3.txt spsidebyside3.txt
ruby isanagram.rb anagram_4.txt spsidebyside4.txt
ruby isanagram.rb anagram_5.txt spsidebyside5.txt
ruby isanagram.rb anagram_6.txt spsidebyside6.txt
ruby isanagram.rb anagram_7.txt spsidebyside7.txt
ruby isanagram.rb anagram_8.txt spsidebyside8.txt
ruby isanagram.rb anagram_9.txt spsidebyside9.txt
#ruby isanagram.rb anagram_10.txt spsidebyside10.txt
ruby isanagram.rb anagram_11.txt spsidebyside11.txt
ruby isanagram.rb anagram_12.txt spsidebyside12.txt
ruby isanagram.rb anagram_13.txt spsidebyside13.txt
#ruby isanagram.rb anagram_14.txt spsidebyside14.txt
ruby isanagram.rb anagram_15.txt spsidebyside15.txt
#ruby isanagram.rb anagram_16.txt spsidebyside16.txt
ruby isanagram.rb anagram_17.txt spsidebyside17.txt
ruby isanagram.rb anagram_18.txt spsidebyside18.txt
ruby isanagram.rb anagram_19.txt spsidebyside19.txt
ruby isanagram.rb anagram_20.txt spsidebyside20.txt
ruby isanagram.rb anagram_21.txt spsidebyside21.txt
ruby isanagram.rb anagram_22.txt spsidebyside22.txt
ruby isanagram.rb anagram_23.txt spsidebyside23.txt
ruby isanagram.rb anagram_24.txt spsidebyside24.txt
ruby isanagram.rb anagram_25.txt spsidebyside25.txt
ruby isanagram.rb anagram_26.txt spsidebyside26.txt
ruby isanagram.rb anagram_27.txt spsidebyside27.txt
ruby isanagram.rb anagram_28.txt spsidebyside28.txt
ruby isanagram.rb anagram_29.txt spsidebyside29.txt
ruby isanagram.rb anagram_30.txt spsidebyside30.txt
#ruby isanagram.rb anagram_31.txt spsidebyside31.txt
ruby isanagram.rb anagram_32.txt spsidebyside32.txt
ruby isanagram.rb anagram_33.txt spsidebyside33.txt
ruby isanagram.rb anagram_34.txt spsidebyside34.txt
ruby isanagram.rb anagram_35.txt spsidebyside35.txt
ruby isanagram.rb anagram_36.txt spsidebyside36.txt
ruby isanagram.rb anagram_37.txt spsidebyside37.txt
ruby isanagram.rb anagram_38.txt spsidebyside38.txt
ruby isanagram.rb anagram_39.txt spsidebyside39.txt
ruby isanagram.rb anagram_40.txt spsidebyside40.txt
